[build]
  functions = "netlify/functions"

[[redirects]]
  from = "/:character/:emotion"
  to = "/.netlify/functions/random-image?character=:character&emotion=:emotion"
  status = 302  # ここを200から302に変更
  force = true

[[redirects]]
  from = "/:character/:emotion/:number"
  to = "/:character/:emotion/:number"
  status = 200
